"""Generate theme.css and slots.json from a handoff payload.

Runs inside the matrix-handoff GitHub Actions workflow. Reads SUMMARY,
NOTES_JSON, HANDOFF_ID, ANTHROPIC_API_KEY from env, calls the Anthropic
Messages API, parses the response, writes ./artifact/theme.css and
./artifact/slots.json.

Falls back to a deterministic stub artifact if the API key is missing or
the API call fails — so the workflow always produces SOMETHING the server's
linter can ingest, rather than failing the whole cycle.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ANTHROPIC_URL = "https://api.anthropic.com/v1/messages"
MODEL = os.environ.get("ANTHROPIC_MODEL") or "claude-sonnet-4-5"
MAX_TOKENS = 3000

PROMPT_TEMPLATE = """You are restyling a whimsical post-it-note web app called \
TheMatrix. Each cycle, the top user-voted prompts are summarised here:

CYCLE SUMMARY:
{summary}

TOP USER PROMPTS THIS CYCLE:
{notes}

Produce TWO outputs separated by the line "---SPLIT---".

PART 1 — A complete CSS file (theme.css). Hard rules:
  * NO @import. NO url(...) pointing to anything starting with http:, https:,
    //, or data:. NO expression(). NO -moz-binding. NO behaviour:.
  * Only standard CSS. No JavaScript.
  * Targets you can style: body, header, h1, .countdown, .big-clock, .note,
    .note textarea, button, .toast, #generation-attraction.
  * Aim for visually striking but readable. Honour the spirit of the prompts.
  * Stay under 4 KB of CSS.

PART 2 — A JSON object (slots.json) with exactly these string keys:
  "intro"        — short HTML for the page intro (1-2 sentences)
  "aside"        — short HTML for an aside note
  "footer-extra" — short HTML for footer flavour text
  Each value: plain text + only these inline tags <em>, <strong>, <br>.
  NO <script>, NO event handlers (on*=), NO inline style attributes.
  Each value under 200 characters.

Output format — exactly this, no markdown fences, no commentary:
<theme.css contents>
---SPLIT---
{{"intro": "...", "aside": "...", "footer-extra": "..."}}
"""


def _strip_code_fence(text: str) -> str:
    """Remove a leading/trailing ``` fence if the model added one."""
    text = text.strip()
    if text.startswith("```"):
        # drop opening fence (with optional language tag)
        first_nl = text.find("\n")
        if first_nl != -1:
            text = text[first_nl + 1:]
    if text.endswith("```"):
        text = text[:-3].rstrip()
    return text.strip()


def call_anthropic(prompt: str) -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not set")
    body = {
        "model": MODEL,
        "max_tokens": MAX_TOKENS,
        "messages": [{"role": "user", "content": prompt}],
    }
    req = urllib.request.Request(
        ANTHROPIC_URL,
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    blocks = payload.get("content") or []
    return "".join(b.get("text", "") for b in blocks if b.get("type") == "text")


def fallback_artifact(summary: str, notes: list[dict]) -> tuple[str, dict]:
    """Deterministic stub used when the API is unavailable. Mirrors the
    palette logic in MockGithubAgent so the page never goes blank."""
    seed = int(hashlib.sha256(summary.encode("utf-8")).hexdigest(), 16)
    palette = [
        ("#fff5f7", "#ff7faa", "#34495e"),
        ("#f4fff5", "#5fb37c", "#2f4f3a"),
        ("#fffaf0", "#e08a3c", "#5a3a14"),
        ("#f0f4ff", "#6d83d9", "#1f2a55"),
        ("#fdf5ff", "#a25fb3", "#3c1f4a"),
    ]
    bg, accent, ink = palette[seed % len(palette)]
    rotation = (seed % 7) - 3
    css = (
        f"body {{ background: {bg}; color: {ink}; }}\n"
        f"h1 {{ color: {accent}; transform: rotate({rotation}deg); }}\n"
        f".note {{ background: {bg}; border-color: {accent}; }}\n"
        f"button {{ background: {accent}; }}\n"
        f"#generation-attraction {{ border-color: {accent}; }}\n"
    )
    top = "your prompts"
    for n in notes:
        text = (n.get("text") or "").strip()
        if text:
            top = text[:60]
            break
    slots = {
        "intro": f"<p>This cycle reflects: <em>{top}</em>.</p>",
        "aside": "<p>Generated by the fallback stub — no API key.</p>",
        "footer-extra": f"<p><em>seed {seed % 100000}</em></p>",
    }
    return css, slots


def parse_response(text: str) -> tuple[str, dict]:
    parts = text.split("---SPLIT---", 1)
    if len(parts) != 2:
        raise ValueError(f"missing ---SPLIT--- separator. Got: {text[:200]!r}")
    css = _strip_code_fence(parts[0])
    slots_raw = _strip_code_fence(parts[1])
    # Pull just the JSON object if the model added trailing chatter
    match = re.search(r"\{.*\}", slots_raw, re.DOTALL)
    if not match:
        raise ValueError(f"could not find JSON object in: {slots_raw[:200]!r}")
    slots = json.loads(match.group(0))
    if not isinstance(slots, dict):
        raise ValueError("slots payload is not a JSON object")
    return css, slots


def main() -> int:
    summary = (os.environ.get("SUMMARY") or "no summary").strip()
    notes_json = os.environ.get("NOTES_JSON") or "[]"
    handoff_id = os.environ.get("HANDOFF_ID") or "unknown"
    try:
        notes = json.loads(notes_json)
        if not isinstance(notes, list):
            notes = []
    except json.JSONDecodeError:
        notes = []

    notes_block = "\n".join(
        f"- {(n.get('text') or '').strip()} (votes: {int(n.get('votes', 0))})"
        for n in notes if isinstance(n, dict) and (n.get("text") or "").strip()
    ) or "- (no prompts this cycle)"
    prompt = PROMPT_TEMPLATE.format(summary=summary, notes=notes_block)

    try:
        raw = call_anthropic(prompt)
        css, slots = parse_response(raw)
        print(f"[generate_artifact] OK from API: css={len(css)}B, slots keys={list(slots)}")
    except (RuntimeError, urllib.error.URLError, urllib.error.HTTPError,
            ValueError, json.JSONDecodeError, TimeoutError) as exc:
        print(f"[generate_artifact] FALLBACK ({type(exc).__name__}: {exc})", file=sys.stderr)
        css, slots = fallback_artifact(summary, notes)

    out = Path("artifact")
    out.mkdir(parents=True, exist_ok=True)
    (out / "theme.css").write_text(css, encoding="utf-8")
    (out / "slots.json").write_text(json.dumps(slots, indent=2), encoding="utf-8")
    print(f"[generate_artifact] wrote artifact/ for handoff {handoff_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
